spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${db_url}
    username: ${db_user}
    password: ${db_password}
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
  mvc:
    throw-exception-if-no-handler-found: true

  external:
    service:
      base-url: ${mockApi_url}
  web:
    resources:
      add-mappings: false