spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${dbLocal_url}
    username: ${dbLocal_user}
    password: ${dbLocal_password}
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
  mvc:
    throw-exception-if-no-handler-found: true

  external:
    service:
      base-url: "https://6463935f127ad0b8f88ba6ee.mockapi.io/carpinchoStore"
  web:
    resources:
      add-mappings: false