spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${dbLocal_url}
    username: ${dbLocal_user}
    password: ${dbLocal_password}
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true